name: GitHub-Profile-Summary-Cards
on:
  schedule:
    - cron: "0 0 * * *"     # 매일 00:00 UTC에 갱신 (한국 09:00)
  workflow_dispatch:        # 필요시 수동 실행

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: 8parks          
          BRANCH_NAME: "main"                
          UTC_OFFSET: 9                      # 한국 시간
          # 필요시 제외할 언어(쉼표 구분): 
          EXCLUDE: ""
          # 이미지 자동 커밋/푸시
          AUTO_PUSH: true
          # 테마 바꾸고 싶으면 아래 theme 파라미터 추가
          # THEME: "tokyonight"
